# Datasource - H2 default (Dev Services will auto-start in dev/test)
quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Logging
quarkus.log.category."org.springframework".level=INFO

# Cache
quarkus.cache.enabled=true

# Health
quarkus.smallrye-health.ui.always-include=true

# MySQL profile
%mysql.quarkus.datasource.db-kind=mysql
%mysql.quarkus.datasource.jdbc.url=${MYSQL_URL:jdbc:mysql://localhost/petclinic}
%mysql.quarkus.datasource.username=${MYSQL_USER:petclinic}
%mysql.quarkus.datasource.password=${MYSQL_PASS:petclinic}
%mysql.quarkus.hibernate-orm.database.generation=none
%mysql.quarkus.hibernate-orm.sql-load-script=db/mysql/data.sql

# Postgres profile
%postgres.quarkus.datasource.db-kind=postgresql
%postgres.quarkus.datasource.jdbc.url=${POSTGRES_URL:jdbc:postgresql://localhost/petclinic}
%postgres.quarkus.datasource.username=${POSTGRES_USER:petclinic}
%postgres.quarkus.datasource.password=${POSTGRES_PASS:petclinic}
%postgres.quarkus.hibernate-orm.database.generation=none
%postgres.quarkus.hibernate-orm.sql-load-script=db/postgres/data.sql
